import type { Metadata } from "next";
import { ReactNode } from "react";

import "@/styles/globals.css";

import { geistSans } from "@/common/libs/fonts";
import { cn } from "@/common/libs/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body className={cn("font-geist", geistSans.variable)}>{children}</body>
    </html>
  );
}
